version: '3.3'

services:
  demo:
    build:
      context: .
      dockerfile: apache.dockerfile
    image: apache:bbr
    ports:
      - "80:80"
    volumes:
      - ../web:/var/www/html/
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

