version: '3.3'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache:bbr
    ports:
      - "80:80"
    volumes:
      - ../web:/var/www/html/
      - ./default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

