# node/Dockerfile
# kan ikke køre selvstændigt men grundlag for projekt specifik Dockerfile
# Der er fra version 4.8 til 4.9 skiftet fra alpine til apache

FROM phpmyadmin/phpmyadmin:5.0

# RUN apk update && apk add -q nano
RUN apt update && apt install -y nano


