version: '3.7'
# NB det er kun src/index.html filen, der kan vises da php-fpm ikke er implementeret
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:bbr
    container_name: web
    ports:
      - "80:80"
    volumes:
      - phpsocket:/run/php/
      - ../web:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_fpm:bbr
    container_name: php
    volumes:
      - phpsocket:/run/php/
      - ../web:/var/www/html
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

volumes:
  phpsocket:
    external: true

