version: '3.3'
# NB det er kun src/index.html filen, der kan vises da php-fpm ikke er implementeret
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:bbr
    ports:
      - "80:80"
    volumes:
      - phpsocket:/run/php/
      - ../web:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

volumes:
  phpsocket:
    external: true

