version: '3.3'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:bbr
    ports:
      - "80:80"
    volumes:
      - ../web:/usr/share/nginx/html
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

