version: '3.3'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:bbr
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - phpsocket:/run/php/
      - ../web/:/var/www/html/
      #      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

    networks:
      - default

  php:
    image: php_fpm:bbr
    volumes:
      - phpsocket:/run/php/
      - ../web/:/var/www/html/
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    container_name: php
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

volumes:
  phpsocket:
    external: true