version: '3.3'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:bbr
    ports:
      - "80:80"
    volumes:
      - ../web:/usr/local/apache2/htdocs
#      - ./default.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

