version: '3.3'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: httpd:bbr
    ports:
      - "80:80"
    volumes:
      - phpsocket:/sock
      - ../web:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    networks:
      - default

networks:
  default:
    external:
      name: humle_net

volumes:
  phpsocket:
    external: true