# Use root/example as user/password credentials
version: '3.6'

services:

  mysql:
    image: mysql:bbr
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: bookstore
    volumes:
    - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bookstore
      MYSQL_USER: athlon38
      MYSQL_PASSWORD: trine-73-glf
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:bbr
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - 8080:80
    networks:
      - default

networks:
    default:
        external:
            name: humle_net

volumes:
    mysqldata:
      external: true
