version: '3.6'
# NB det er kun src/index.html filen, der kan vises da php-fpm ikke er implementeret
services:
  web:
    image: openresty:bbr
    container_name: web
    volumes:
      - phpsocket:/run/php/
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../web:/usr/local/openresty/nginx/html
    ports:
      - "80:80"
    networks:
      - default

  php:
    image: php_fpm:bbr
    container_name: php
    volumes:
      - phpsocket:/run/php/
      - ../web:/usr/local/openresty/nginx/html
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - default

volumes:
  phpsocket:
    external: true

networks:
  default:
    external:
      name: humle_net
